name: Release Build

on:
  push:
    tags:
      - 'v*'  #e.g., v1.0, v1.1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create build
        run: |
          echo "Release build v1" > release.txt

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.secret_artifact }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.secret_artifact }}
