name: Upload Artifact Demo

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # <-- Add this line to allow release creation

jobs:
  artifact-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Simulate a build
        run: echo "Build complete!" > build.log

      - name: Upload build artifact with retention
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
          retention-days: 30

  release:
    needs: artifact-demo
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-logs

      - name: Create GitHub releases
        id: create_releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.0.0
          name: Release v2.0.0
          body: "Automated release with build log."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact as release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.0.0  # Make sure tag matches!
          files: build.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
