name: Build and Release on Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate build
        run: echo "Build complete at $(date)" > build.log

      - name: Create Release (with dynamic tag)
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: main-$(date +%s)
          name: "Main Branch Auto Release"
          body: "Auto release from main branch."
