name: Build and Release on Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate build
        run: echo "Build complete at $(date)" > build.log

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: main-$(date +%s)
          name: "Auto Release from Main"
          body: "This is an automated release from the main branch."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_release.outputs.tag_name }}
          files: build.log
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
