name: Simple Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Simulate a build
        run: |
          echo "Build complete!" > build.log

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
