name: Build and Release

on:
  push:
    tags:
      - 'v*'  # This will only run when you push a tag like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate build
        run: echo "Build completed at $(date)" > build.log

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body: "Automated release with build log"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
